name: CI

on: [push]

jobs:
  test-spec:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install Project
        run: npm ci
      - name: Run Unit Tests
        run: npm test
        env:
          CI: true
      - name: Upload CodeCoverage
        uses: codecov/codecov-action@master
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage/*.json
          flags: unittests

  build:
    name: Build
    needs: [test-spec]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Run Build
        run: |
          npm ci
          npm run build
        env:
          CI: true
